image: golang:latest

stages:
    - build

build:
    variables:
        PESCA_PROD: 1
    stage: build
    script:
        - bash ./scripts/build.sh
    artifacts:
        paths:
            - bin/*
