image: golang:latest

stages:
    - test
    - build

test:
    stage: test
    script:
        - go test ./... -race

build:
    variables:
        PESCA_PROD: 1
    stage: build
    script:
        - bash ./scripts/build.sh
    artifacts:
        paths:
            - bin/*
